name: jenkins
services:
  jenkins:
    image: jenkins/jenkins:jdk21
    ports:
      - 5000:5000
      - 8080:8080
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      SELENOID_REMOTE_URL: http://selenoid:4444/wd/hub
    networks:
      - default
  selenoid:
    image: aerokube/selenoid:latest
    expose:
      - 4444
    ports:
      - 4444:4444
    volumes:
      - ./:/etc/selenoid/ # assumed current dir contains browsers.json
      - "//var/run/docker.sock:/var/run/docker.sock"
    command: [ "-container-network", "jenkins_default"]
    networks:
      - default
  selenoid-ui:
    image: aerokube/selenoid-ui:1.10.11
    ports:
      - 8082:8080
    links:
      - selenoid
    command: [ "--selenoid-uri", "http://selenoid:4444" ]
    networks:
      - default
volumes:
  jenkins_home:

networks:
  default: